;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-complete-previous
	evil-delete-char
	evil-insert
	evil-next-line
	evil-normal-state
	multiple-cursors-hydra/body
	multiple-cursors-hydra/mc/mark-next-like-this
	multiple-cursors-hydra/mc/mark-previous-like-this
	multiple-cursors-hydra/mc/unmark-next-like-this
	multiple-cursors-hydra/mc/unmark-previous-like-this
	))

(setq mc/cmds-to-run-once
      '(
	iedit-switch-to-mc-mode
	yaml-electric-backspace
	))
