;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-force-normal-state
	evil-forward-char
	evil-goto-line
	evil-insert
	evil-insert-line
	evil-next-line
	evil-normal-state
	evil-paste-pop-next
	evil-previous-line
	evil-sp-delete-line
	evil-visual-char
	evil-yank
	helm-M-x
	indent-for-tab-command
	magit-status
	multiple-cursors-hydra/body
	multiple-cursors-hydra/mc/edit-lines-and-exit
	multiple-cursors-hydra/mc/mark-previous-like-this
	multiple-cursors-hydra/mc/unmark-next-like-this
	multiple-cursors-hydra/mc/unmark-previous-like-this
	org-delete-char
	org-self-insert-command
	org-shiftright
	sp-backward-delete-char
	undefined
	))

(setq mc/cmds-to-run-once
      '(
	evil-delete
	evil-search-next
	flycheck-next-error
	flycheck-previous-error
	multiple-cursors-hydra/mc/mark-next-like-this
	multiple-cursors-hydra/mc/skip-to-next-like-this
	swiper
	))
