(defun cesco/django ()
    (if (projectile-project-p)
        (if (file-exists-p (concat (projectile-project-root) "manage.py"))
            (setq web-mode-engines-alist '(("django" . "\\.html\\'")))
            (message "do not exists")
            )
        )
    )
(add-hook 'web-mode-hook 'cesco/django)
