(defun cesco/django ()
    (if (projectile-project-p)
        (if (file-exists-p (concat (projectile-project-root) "manage.py"))
            (web-mode-set-engine "django")
            (message "do not exists")
            )
        )
    )
(add-hook 'web-mode-hook 'cesco/django)
