* Intro Software P2
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=NWlnYmw1amFtYWxwc21rczA0azZlY2xrMzggZnJhbmNlc2NvYWZlcnJhcm9AbQ][Go to gcal web page]]
  :ID: 5igbl5jamalpsmks04k6eclk38
  :END:

  <2017-07-06 Thu>

  This is a important grade a need to get!
* Storage with Kubernetes on AWS
  :PROPERTIES:
  :LOCATION: BrightTALK
  :LINK: [[https://www.google.com/calendar/event?eid=N2gyY3E2ZWNwdWs1cTJtZm5iZzRncWhlbGcgZnJhbmNlc2NvYWZlcnJhcm9AbQ][Go to gcal web page]]
  :ID: 7h2cq6ecpuk5q2mfnbg4gqhelg
  :END:

  <2017-07-11 Tue 14:00-15:00>

Click here to attend: http://www.brighttalk.com/webcast/14601/267015?utm_campaign=google-calendar&utm_source=brighttalk-portal&utm_medium=calendar

Containers may be great for running stateless applications, but what about stateful applications? Kubernetes, the open-source platform for managing containers at scale, contains various technologies to provide persistent storage for stateful applications. This allows users to manage their stateful applications and gain all of the benefits of a containerized infrastructure.

Join us as we discuss storage technologies in Kubernetes. We will cover PersistentVolumes, PersistentVolumeClaims, dynamic provisioning, StorageClasses, StatefulSets, and other technologies which help users deploy their stateful applications on Kubernetes running on Amazon Web Services. We will also demonstrate how to run CockroachDB, Wordpress/MySQL, and GlusterFS deployed as containers using Kubernetes on AWS.
